Repository supboom/open-pixel-art, pull requests merged in 2022-10, with the labels that each got.

#2 Update dangerfile.test.js
  __tests__/dangerfile.test.js
Labels: hactoberfest-accepted

#1 Update dangerfile.test.js
  __tests__/dangerfile.test.js
Labels: hactoberfest-accepted

#4 Update sortPixels.js
  scripts/sortPixels.js
Labels: hactoberfest-accepted

#3 Update name-hover.js
  assets/javascript/name-hover.js
Labels: hactoberfest-accepted

#5 Update sync.js
  scripts/sync.js
Labels: hactoberfest-accepted

#6 Update party-mode.js
  assets/javascript/party-mode.js
Labels: hactoberfest-accepted

#7 Update dangerfile.test.js
  __tests__/dangerfile.test.js
Labels: good first issue, hacktoberfest-accepted

#8 Update mergePixels.test.js
  __tests__/scripts/mergePixels.test.js
Labels: enhancement, hacktoberfest-accepted

#10 Update env.js
  _data/env.js
Labels: hacktoberfest-accepted

#9 Update data.test.js
  __tests__/data.test.js
Labels: hacktoberfest-accepted

#13 Update data.test.js
  __tests__/data.test.js
Labels: hacktoberfest-accepted

#15 Update name-hover.js
  assets/javascript/name-hover.js
Labels: good first issue, hacktoberfest-accepted

#12 Update defaults.json
  _data/defaults.json
Labels: hacktoberfest-accepted

#11 Update env.js
  _data/env.js
Labels: hacktoberfest-accepted

#14 Update dangerfile.test.js
  __tests__/dangerfile.test.js
Labels: hacktoberfest-accepted
